[platformio]
default_envs = esp8266_nodemcu
src_dir = ESP_Hover_Browser

[env]
frameworks = arduino
monitor_speed = 115200

[env:esp8266_esp01_ledpin1]
platform = espressif8266
board = esp01_1m
build_flags = -DENV_HOVERSERVO_ESP8266_ESP01_LEDPIN1_V0
lib_deps =
    https://github.com/gilmaimon/ArduinoWebsockets.git
    https://github.com/me-no-dev/ESPAsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git

[env:esp8266_esp01_ledpin2]
platform = espressif8266
board = esp01_1m
build_flags = -DENV_HOVERSERVO_ESP8266_ESP01_LEDPIN2_V0
lib_deps =
    https://github.com/gilmaimon/ArduinoWebsockets.git
    https://github.com/me-no-dev/ESPAsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git

[env:esp8266_lolin_d1_mini]
platform = espressif8266
board = d1_mini
build_flags = -DENV_HOVERSERVO_ESP8266_LOLIND1MINILITE
lib_deps =
    https://github.com/gilmaimon/ArduinoWebsockets.git
    https://github.com/me-no-dev/ESPAsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git

[env:esp8266_nodemcu]
platform = espressif8266
board = nodemcu
build_flags = -DENV_HOVERSERVO_ESP8266_NODEMCU
lib_deps =
    https://github.com/gilmaimon/ArduinoWebsockets.git
    https://github.com/me-no-dev/ESPAsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git

[env:esp8266_esp01_ledpin2_gyro]
platform = espressif8266
board = esp01_1m
build_flags = -DENV_HOVERSERVOGYRO_ESP8266_ESP01_LEDPIN2_V0
lib_deps =
    https://github.com/gilmaimon/ArduinoWebsockets.git
    https://github.com/me-no-dev/ESPAsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/LiquidCGS/FastIMU.git

[env:esp32c3_supermini_ws2812fx]
platform = espressif32
board = esp32-c3-devkitm-1
build_flags = -DENV_HOVERSERVOGYRO_ESP32C3_SUPERMINI_WS2812FX_V0
lib_deps =
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/madhephaestus/ESP32Servo.git
    https://github.com/gilmaimon/ArduinoWebsockets.git
    https://github.com/dvarrel/ESPAsyncWebSrv.git
    https://github.com/kitesurfer1404/WS2812FX.git
    https://github.com/LiquidCGS/FastIMU.git

[env:esp32c3_wroom_v1]
platform = espressif32
board = esp32-c3-devkitm-1
build_flags = -DENV_HOVERSERVOGYRO_ESP32C3_WROOM_V1
lib_deps =
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/madhephaestus/ESP32Servo.git
    https://github.com/gilmaimon/ArduinoWebsockets.git
    https://github.com/dvarrel/ESPAsyncWebSrv.git
    https://github.com/LiquidCGS/FastIMU.git
